version: '3.3'
services:
  compa.authenticator:
    build: pbft-master-origin-master
    volumes:
      - ./pbft-master-origin-master:/app
      - ./simplesamlphp:/code
      - ./idp:/conf
    environment:
      - SIMPLESAMLPHP_CONFIG_DIR=/conf/
      - COUNTS=6
      - QUORUMS=4
      - EVILS=1
      - IS_AGENT=1
    networks:
      - default

  idp.zengo.saml:
    build: build
    volumes:
      - ./simplesamlphp:/code
      - ./idp:/conf
    working_dir: /code
    environment:
      - SIMPLESAMLPHP_CONFIG_DIR=/conf/
    networks:
      - default

  sp.zengo.saml:
    build: build
    hostname: sp
    volumes:
      - ./simplesamlphp:/code
      - ./sp1:/conf
    working_dir: /code
    environment:
      - SIMPLESAMLPHP_CONFIG_DIR=/conf/
    command: apache2 -D FOREGROUND
    networks:
      - default

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: sessions
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - default

  redis:
    image: redis
    networks:
      - default

  gencert:
    image: cfssl/cfssl
    volumes:
      - .:/work
    working_dir: /work
    entrypoint: /bin/bash
    command:
      - ./ca/generate.sh
    networks:
      - default

  nginx:
    image: nginx:stable
    volumes:
      - ./nginx:/etc/nginx:ro
    ports:
      - '80:80'
      - '443:443'
    networks:
      - default

  server.signer:
    build: signers
    volumes:
      - ./signers/script:/script
      - ./signer.server/gencert.py:/gencert.py
      - ./simplesamlphp/cert:/cert
    environment:
      - IS_SERVER=1
      - PARTIES
    networks:
      - default

  1_client.signer:
    build: signers
    volumes:
      - ./signers/script:/script
    environment:
      - PARTIES
    networks:
      - default

  2_client.signer:
    build: signers
    volumes:
      - ./signers/script:/script
    environment:
      - PARTIES
    networks:
      - default

#  java.server:
#    build: java-server
#    volumes:
#      - ./java-server:/app
#      - ./simplesamlphp:/code
#    environment:
#      - SIMPLESAMLPHP_CONFIG_DIR=/conf/
#      - IS_AGENT=1
#    networks:
#      - default

networks:
  default:
